-- ============================================
-- RentBase MVP - Supabase Database Schema
-- ============================================

-- Create the rentbase schema
create schema if not exists rentbase;

-- ============================================
-- 1. PROFILES (Synced with Auth)
-- ============================================
create table rentbase.profiles (
  id uuid references auth.users on delete cascade primary key,
  phone_number text unique not null,
  role text default 'renter' check (role in ('renter', 'agent', 'admin')),
  is_verified boolean default false,
  created_at timestamptz default now()
);

-- ============================================
-- 2. REVIEWS (Agent Checker)
-- ============================================
create table rentbase.reviews (
  id bigint generated by default as identity primary key,
  agent_phone text not null,
  reviewer_id uuid references rentbase.profiles(id),
  rating int check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamptz default now()
);

-- Index for fast agent lookup
create index idx_reviews_agent_phone on rentbase.reviews (agent_phone);

-- ============================================
-- 3. TRANSACTIONS (Paystack Ledger)
-- ============================================
create table rentbase.transactions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references rentbase.profiles(id),
  reference text unique not null, -- Paystack Reference
  amount numeric not null,
  status text default 'pending' check (status in ('pending', 'success', 'failed')),
  feature_type text not null check (feature_type in ('contract', 'deposit_report')),
  created_at timestamptz default now()
);

-- ============================================
-- 4. CONTRACTS (Pocket Lawyer)
-- ============================================
create table rentbase.contracts (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references rentbase.profiles(id),
  customer_email text, -- For anonymous users who haven't signed up
  payment_ref text references rentbase.transactions(reference),
  details jsonb, -- Store form inputs
  is_finalized boolean default false, -- False = Draft Mode
  
  -- Digital Signature Fields
  landlord_signature text, -- Base64 encoded signature image
  landlord_signed_at timestamptz,
  landlord_sign_token uuid default gen_random_uuid(), -- Unique token for signing link
  tenant_signature text, -- Base64 encoded signature image
  tenant_signed_at timestamptz,
  tenant_sign_token uuid default gen_random_uuid(), -- Unique token for signing link
  is_fully_signed boolean default false, -- True when both parties have signed
  
  created_at timestamptz default now()
);

-- Index for customer email lookup (for anonymous users)
create index idx_contracts_customer_email on rentbase.contracts (customer_email);

-- Index for signing tokens
create index idx_contracts_landlord_token on rentbase.contracts (landlord_sign_token);
create index idx_contracts_tenant_token on rentbase.contracts (tenant_sign_token);

-- ============================================
-- 5. CONDITION REPORTS (Deposit Shield)
-- ============================================
create table rentbase.condition_reports (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references rentbase.profiles(id),
  customer_email text, -- For anonymous users
  payment_ref text references rentbase.transactions(reference),
  property_address text,
  report_type text, -- 'move_in' or 'move_out'
  is_finalized boolean default false,
  report_date timestamptz default now()
);

-- Index for customer email lookup
create index idx_condition_reports_customer_email on rentbase.condition_reports (customer_email);

create table rentbase.report_images (
  id bigint generated by default as identity primary key,
  report_id uuid references rentbase.condition_reports(id) on delete cascade,
  image_url text not null,
  room_name text,
  defect_description text
);

-- ============================================
-- 6. AUTO-CREATE PROFILE ON SIGNUP (Trigger)
-- ============================================
create or replace function rentbase.handle_new_user()
returns trigger as $$
begin
  insert into rentbase.profiles (id, phone_number)
  values (new.id, new.phone);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function rentbase.handle_new_user();

-- ============================================
-- 7. ROW LEVEL SECURITY (RLS)
-- ============================================

-- Enable RLS on all tables
alter table rentbase.profiles enable row level security;
alter table rentbase.reviews enable row level security;
alter table rentbase.transactions enable row level security;
alter table rentbase.contracts enable row level security;
alter table rentbase.condition_reports enable row level security;
alter table rentbase.report_images enable row level security;

-- PROFILES Policies
create policy "Users can view own profile"
  on rentbase.profiles for select
  using (auth.uid() = id);

create policy "Users can update own profile"
  on rentbase.profiles for update
  using (auth.uid() = id);

-- REVIEWS Policies
create policy "Anyone can read reviews"
  on rentbase.reviews for select
  using (true);

create policy "Authenticated users can create reviews"
  on rentbase.reviews for insert
  with check (auth.uid() = reviewer_id);

-- TRANSACTIONS Policies
create policy "Users can view own transactions"
  on rentbase.transactions for select
  using (auth.uid() = user_id);

create policy "Users can create transactions"
  on rentbase.transactions for insert
  with check (auth.uid() = user_id);

-- CONTRACTS Policies
-- Allow anyone to view their own contracts (authenticated)
create policy "Users can view own contracts"
  on rentbase.contracts for select
  using (auth.uid() = user_id);

-- Allow anyone to preview drafts by ID (for sharing via link)
create policy "Public can preview drafts by ID"
  on rentbase.contracts for select
  using (is_finalized = false);

-- Allow finalized contracts to be viewed by email match (for anonymous users)
create policy "Email owners can view finalized contracts"
  on rentbase.contracts for select
  using (is_finalized = true and customer_email is not null);

-- Allow anyone (including anonymous) to create contract drafts
create policy "Anyone can create contract drafts"
  on rentbase.contracts for insert
  with check (true);

-- Allow authenticated users to update their own contracts
create policy "Users can update own contracts"
  on rentbase.contracts for update
  using (auth.uid() = user_id);

-- Allow anonymous contracts to be updated (before finalization)
create policy "Anyone can update draft contracts"
  on rentbase.contracts for update
  using (user_id is null and is_finalized = false);

-- CONDITION REPORTS Policies
-- Authenticated users can view their own reports
create policy "Users can view own reports"
  on rentbase.condition_reports for select
  using (auth.uid() = user_id);

-- Anyone can create report drafts (for anonymous users)
create policy "Anyone can create report drafts"
  on rentbase.condition_reports for insert
  with check (true);

-- Public can preview drafts by ID (for sharing)
create policy "Public can preview report drafts"
  on rentbase.condition_reports for select
  using (is_finalized = false);

-- Email owners can view finalized reports
create policy "Email owners can view finalized reports"
  on rentbase.condition_reports for select
  using (is_finalized = true);

-- Users can update own reports
create policy "Users can update own reports"
  on rentbase.condition_reports for update
  using (auth.uid() = user_id);

-- Anyone can update draft reports (before finalization)
create policy "Anyone can update draft reports"
  on rentbase.condition_reports for update
  using (user_id is null and is_finalized = false);

-- REPORT IMAGES Policies
-- Users can view images from their own reports
create policy "Users can view own report images"
  on rentbase.report_images for select
  using (
    report_id in (
      select id from rentbase.condition_reports where user_id = auth.uid()
    )
  );

-- Anyone can view report images (for previews)
create policy "Anyone can view report images"
  on rentbase.report_images for select
  using (true);

-- Anyone can insert report images (for anonymous users)
create policy "Anyone can insert report images"
  on rentbase.report_images for insert
  with check (true);

-- Users can delete their own report images
create policy "Users can delete own report images"
  on rentbase.report_images for delete
  using (
    report_id in (
      select id from rentbase.condition_reports where user_id = auth.uid()
    )
  );

-- Anyone can delete images from draft reports
create policy "Anyone can delete draft report images"
  on rentbase.report_images for delete
  using (
    report_id in (
      select id from rentbase.condition_reports where user_id is null and is_finalized = false
    )
  );

-- ============================================
-- 8. STORAGE BUCKET
-- ============================================

-- Create storage bucket for deposit photos
insert into storage.buckets (id, name, public)
values ('deposit-photos', 'deposit-photos', true)
on conflict (id) do nothing;

-- Storage policy: Anyone can upload deposit photos (for anonymous users)
create policy "Anyone can upload deposit photos"
  on storage.objects for insert
  with check (bucket_id = 'deposit-photos');

-- Storage policy: Anyone can view photos (for report generation)
create policy "Public can view deposit photos"
  on storage.objects for select
  using (bucket_id = 'deposit-photos');
