-- ============================================
-- RentBase MVP - Supabase Database Schema
-- ============================================

-- ============================================
-- 1. PROFILES (Synced with Auth)
-- ============================================
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  phone_number text unique not null,
  role text default 'renter' check (role in ('renter', 'agent', 'admin')),
  is_verified boolean default false,
  created_at timestamptz default now()
);

-- ============================================
-- 2. REVIEWS (Agent Checker)
-- ============================================
create table public.reviews (
  id bigint generated by default as identity primary key,
  agent_phone text not null,
  reviewer_id uuid references public.profiles(id),
  rating int check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamptz default now()
);

-- Index for fast agent lookup
create index idx_reviews_agent_phone on public.reviews (agent_phone);

-- ============================================
-- 3. TRANSACTIONS (Paystack Ledger)
-- ============================================
create table public.transactions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id),
  reference text unique not null, -- Paystack Reference
  amount numeric not null,
  status text default 'pending' check (status in ('pending', 'success', 'failed')),
  feature_type text not null check (feature_type in ('contract', 'deposit_report')),
  created_at timestamptz default now()
);

-- ============================================
-- 4. CONTRACTS (Pocket Lawyer)
-- ============================================
create table public.contracts (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id),
  payment_ref text references public.transactions(reference),
  details jsonb, -- Store form inputs
  is_finalized boolean default false, -- False = Draft Mode
  created_at timestamptz default now()
);

-- ============================================
-- 5. CONDITION REPORTS (Deposit Shield)
-- ============================================
create table public.condition_reports (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id),
  payment_ref text references public.transactions(reference),
  is_finalized boolean default false,
  report_date timestamptz default now()
);

create table public.report_images (
  id bigint generated by default as identity primary key,
  report_id uuid references public.condition_reports(id) on delete cascade,
  image_url text not null,
  defect_description text
);

-- ============================================
-- 6. AUTO-CREATE PROFILE ON SIGNUP (Trigger)
-- ============================================
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, phone_number)
  values (new.id, new.phone);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================
-- 7. ROW LEVEL SECURITY (RLS)
-- ============================================

-- Enable RLS on all tables
alter table public.profiles enable row level security;
alter table public.reviews enable row level security;
alter table public.transactions enable row level security;
alter table public.contracts enable row level security;
alter table public.condition_reports enable row level security;
alter table public.report_images enable row level security;

-- PROFILES Policies
create policy "Users can view own profile"
  on public.profiles for select
  using (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- REVIEWS Policies
create policy "Anyone can read reviews"
  on public.reviews for select
  using (true);

create policy "Authenticated users can create reviews"
  on public.reviews for insert
  with check (auth.uid() = reviewer_id);

-- TRANSACTIONS Policies
create policy "Users can view own transactions"
  on public.transactions for select
  using (auth.uid() = user_id);

create policy "Users can create transactions"
  on public.transactions for insert
  with check (auth.uid() = user_id);

-- CONTRACTS Policies
create policy "Users can view own contracts"
  on public.contracts for select
  using (auth.uid() = user_id);

create policy "Public can preview drafts by ID"
  on public.contracts for select
  using (is_finalized = false);

create policy "Users can create contracts"
  on public.contracts for insert
  with check (auth.uid() = user_id);

create policy "Users can update own contracts"
  on public.contracts for update
  using (auth.uid() = user_id);

-- CONDITION REPORTS Policies
create policy "Users can view own reports"
  on public.condition_reports for select
  using (auth.uid() = user_id);

create policy "Users can create reports"
  on public.condition_reports for insert
  with check (auth.uid() = user_id);

create policy "Users can update own reports"
  on public.condition_reports for update
  using (auth.uid() = user_id);

-- REPORT IMAGES Policies
create policy "Users can view own report images"
  on public.report_images for select
  using (
    report_id in (
      select id from public.condition_reports where user_id = auth.uid()
    )
  );

create policy "Users can insert report images"
  on public.report_images for insert
  with check (
    report_id in (
      select id from public.condition_reports where user_id = auth.uid()
    )
  );

create policy "Users can delete own report images"
  on public.report_images for delete
  using (
    report_id in (
      select id from public.condition_reports where user_id = auth.uid()
    )
  );

-- ============================================
-- 8. STORAGE BUCKET
-- ============================================

-- Create storage bucket for deposit photos
insert into storage.buckets (id, name, public)
values ('deposit-photos', 'deposit-photos', true);

-- Storage policy: Users can upload to their own folder
create policy "Users can upload deposit photos"
  on storage.objects for insert
  with check (
    bucket_id = 'deposit-photos' and
    auth.uid()::text = (storage.foldername(name))[1]
  );

-- Storage policy: Anyone can view photos (for report generation)
create policy "Public can view deposit photos"
  on storage.objects for select
  using (bucket_id = 'deposit-photos');
